-- Clean action
newaction {
	trigger     = "clean",
	description = "Removes files generated by the IDE and Premake",
	execute     = function()
		print("Cleaning...")
		os.rmdir("bin")
		os.rmdir("obj")
		os.rmdir(".vs")
		os.remove("Arcade.vcxproj")
		os.remove("Arcade.vcxproj.user")
		os.remove("Arcade.vcxproj.filters")
		os.remove("ArcadeWorkspace.sdf")
		os.remove("ArcadeWorkspace.sln")
		os.remove("ArcadeWorkspace.VC.opendb")
		print("Done cleaning.")
	end
}